### ISSUE TITLE
createSampleJson.py should nicely say it would like a link to SAMADhi

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/CommonTools#10]
for now createSampleJson.py crashes since the setup_env.sh (rightfully) does not mention CMSSW, so does not know where to look for SAMADhi

**Comment by OlivierBondu** [comment]
I don't think this `createSampleJson.py` is actually used by anyone anywhere, if I am not mistaken, any objection to deleting the script altogether ?

**Comment by pieterdavid** [comment]
I'm still using it... (didn't follow all the changes to this part yet, where is the equivalent of this with the analysis json?). Maybe we could change it into an optional feature of `runPostCrab.py`?

**Comment by swertz** [comment]
We don't use it because the task of creating the JSONs for the factories has been moved to `condorTools` which, by the way, will not work either if simply using `setup_env.sh`.

In the end it might still be useful to have that feature as a standalone script, bearing in mind you'll have to be in a CMS environment to be able to run it? And if @pieterdavid uses it that settles the question! ;)

**Comment by OlivierBondu** [comment]
I actually don't remember the use case which lead to opening this issue...

if the script is used, then yes of course let's keep it :) but we can probably close this issue if @pieterdavid confirms it does work correctly ?

**Comment by pieterdavid** [comment]
if it finds SAMADhi (in practice, after `cmsenv`) it works fine indeed, so we can close this issue (we could add a more descriptive error message, or move it to the GridIn or SAMADhi package)

**Comment by OlivierBondu** [comment]
well, this is about creating a json file specifically for CommonTools usage... so it's probably better to keep it here, and add a more descriptive error message :) I'm changing the title of the issue !

**Comment by pieterdavid** [comment]
I can prepare a pull request for that

**Comment by OlivierBondu** [comment]
I assign you to it then, thanks !
