### ISSUE TITLE
[histFactory] Create dictionaries for framework classes

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/CommonTools#18]
We need a way to generate automatically dictionaries for the framework classes and analyzers classes too.

One way is to force the integration of CommonTools inside CMSSW, into the ``cp3_llbb`` folder. This way, it's easy to access to each analyses / framework ``classes.h`` and generate the proper dictionaries for the plotter.

**Comment by swertz** [comment]
What about simply adding them manually to histFactory when someone adds a class to an analysis? In the end it's just a copy-paste, and it's not going to happen 100 times a week...
