### ISSUE TITLE
issue with make

### ISSUE THREAD

**Issue by sdevissc** [cp3-llbb/CommonTools#42]
Dear all,

Trying to setup CommonTools (just cloned the latest version on ingrid), I get, while making:

```
Scanning dependencies of target count
[  7%] Building CXX object CMakeFiles/count.dir/src/countProcessedEvents.cpp.o
[ 14%] Building CXX object CMakeFiles/count.dir/external/src/jsoncpp.cpp.o
Linking CXX executable createProcessedEvents.exe
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/lcg/root/6.02.00-odfocd7/lib/libCore.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/lcg/root/6.02.00-odfocd7/lib/libCore.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
collect2: error: ld returned 1 exit status
make[2]: *** [createProcessedEvents.exe] Error 1
make[1]: *** [CMakeFiles/count.dir/all] Error 2
```

any idea where this comes from?

Simon

**Comment by blinkseb** [comment]
How did you setup your env? It looks like the wrong version of gcc is used (at least not the same used to build ROOT). During the initial cmake, can you check that gcc version is 4.9.1?

**Comment by sdevissc** [comment]
Ok, I find out that doing 

module purge; module load grid/grid_environment_sl6; module load crab/crab3; module load cms/cmssw

leads to gcc 4.8.1 , while cmsenv leads to 4.9.1 . I most probably did the mistake to retype the module/.. command. Sorry for the noise.

Simon
